### PR TITLE
Migration to Hazelcast 3.8 and Wildfly 10.1

### PR DESCRIPTION
**Pull request by rkowalke**
- Migration to Hazelcast 3.8
- Migration of ra.xml to JEE 7 compliant javax.resource.spi annotations
- Fix illegal primitive config property type boolean by wrapper type ("connectionTracingDetail")
- Implement Referenceable
- Add missing @Override annotations for implemented interfaces

Due to provided scope inside hazelcast-jca-rar/pom.xml the dependencies need to be installed as separate modules into wildfly (see attached ZIP file). Would be better to deploy dependencies within the RAR file, by changing scope to compile.
[wildfly-10.1-modules.zip](https://github.com/hazelcast/hazelcast-ra/files/952088/wildfly-10.1-modules.zip)

### CODE REVIEW

**Comment by emre-aydin** [comment]
verify

**Comment by emre-aydin** [comment]
Hi @rkowalke 

Thanks for your contribution. Can you please fix checkstyle errors? You can execute it by using the following command:

```bash
mvn clean verify -P checkstyle
```

**Comment by rkowalke** [comment]
Sorry for the inconvenience, I have fixed the checkstyle errors now.

**Comment by emre-aydin** [comment]
verify

**Comment by phillip-kruger** [comment]
Has this been merged ? I am trying to get ra deployed on Wildfly 10.

**Comment by emre-aydin** [comment]
@phillip-kruger No, it's not merged yet. It's been a busy couple of months, we haven't had the chance to review this yet. Can you please try building the artifact from @rkowalke's branch and try with that? It would be really helpful if you post your feedback here and maybe also review the PR as well.

**Comment by phillip-kruger** [comment]
@emre-aydin Cool no problem. I have already deployed with @rkowalke hazelcast-jca.jar and then the rar deploy fine. I am busy writing a small app to test hazelcast, but at least the deploy is working fine. Will let you know once I tested.

**Comment by phillip-kruger** [comment]
Hi @emre-aydin 
I created a very basic test, and so far so good.
https://github.com/phillip-kruger/wildfly-hazelcast

I'll continue to add examples to that. Let me know if there is anything specific you want to test.

Cheers

**Comment by hasancelik** [comment]
Hi @rkowalke,
Thanks for your contribution . Can you please sign Hazelcast CLA before merging the PR?
https://hazelcast.atlassian.net/wiki/display/COM/Hazelcast+Contributor+Agreement

**Comment by phillip-kruger** [comment]
@emre-aydin is this merged ?

**Comment by emre-aydin** [comment]
@phillip-kruger no it's not, because we haven't received a CLA from @rkowalke yet. It seems we will need to do the same change ourselves and get it merge as it's been a while since we didn't hear from @rkowalke.

**Comment by emre-aydin** [comment]
@phillip-kruger 

It seems we have already done that. Changes in this PR has been merged but not released yet. I'm closing this PR to avoid any further confusion.

**Pull request closed without merging**
